### PR TITLE
docs: added notes about the usage of the action

### LINKED ISSUE #49: docs: mention that action does not works for draft releases
I see @vedantmgoyal2009... Please add a dry-run, that wont create the pull request to msft.

Other issues I faced:
 
- See for example:
https://github.com/gerardog/gsudo/actions/runs/3278755892/jobs/5397905542
Error message not very descriptive. Actual problem was that the release was draft. Maybe add a warning to the docs that draft releases are not eligible.

- https://github.com/gerardog/gsudo/actions/runs/3300408456/jobs/5444962383
```
  remote: Permission to gerardog/winget-pkgs.git denied to gerardog.
  fatal: unable to access 'https://github.com/gerardog/winget-pkgs.git/': The requested URL returned error: 403
  HTTP 401: Personal access tokens with fine grained access do not support the GraphQL API (https://api.github.com/graphql)
  Try authenticating with:  gh auth login
```
  Problem with permissions, I will fix them. but action completed as Success, not fail.

_Originally posted by @gerardog in https://github.com/vedantmgoyal2009/winget-releaser/issues/47#issuecomment-1287444015_

### PR DESCRIPTION
**Pull request by gerardog**
- Mention that the app must exist on WinGet prior to using WinGet Releaser
- #49

### CODE REVIEW

**Comment by gerardog** [comment]
We can add a Prerequisites section if you want.

**Comment by vedantmgoyal9** [comment]
Hi, my house is undergoing renovation, so I'll be able to review & merge after next few weeks. My PC is currently disassembled.

**Comment by gerardog** [comment]
Great.
What may work for you is to go to this PR [files tab](https://github.com/vedantmgoyal2009/winget-releaser/pull/54/files) and read each paragraph, click on the + sign and leave notes and comments. 

image

Can be done from the web.

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @gerardog for docs

**Pull request merged**
