### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by russellbanks**
This PR updates the ReadMe to have much more documentation on WinGet Releaser's usage.

For reference, the ReadMe was created with [ShaanCoding/ReadME-Generator](https://github.com/ShaanCoding/ReadME-Generator) and subsequently modified.

See [russellbanks/winget-releaser/patch-1/README.md](https://github.com/russellbanks/winget-releaser/blob/patch-1/README.md) for a preview of the updated ReadMe.

I wasn't sure how to create a "generic" screenshot of the output of WinGet Releaser, so the screenshot is from my account. If you find another account suitable (or are able to make it more generic), feel free to do so

### CODE REVIEW

**Review by vedantmgoyal9 — CHANGES_REQUESTED** [review]
Logo: https://user-images.githubusercontent.com/83997633/189393292-4a470cc3-38e6-4f91-bee2-1d59e672ec81.svg

**Comment by vedantmgoyal9** [comment]
The screenshot is fine, I've no problems with that 👍🏻

**Review by vedantmgoyal9 — CHANGES_REQUESTED** [review]
I plan to use https://allcontributors.org/docs/en/overview so I think the existing contributing section can be moved to a separate file `CONTRIBUTING.md`. It would also match the Community Standards (https://github.com/vedantmgoyal2009/winget-releaser/community).

**Comment by russellbanks** [comment]
> I plan to use https://allcontributors.org/docs/en/overview so I think the existing contributing section can be moved to a separate file `CONTRIBUTING.md`. It would also match the Community Standards (https://github.com/vedantmgoyal2009/winget-releaser/community).

I've removed the contributing section. The addition of the `CONTRIBUTING.md` should be done either by yourself or in a separate PR.

**Comment by vedantmgoyal9** [comment]
You can add it in a separate PR so that I can merge it right away.

**Review by vedantmgoyal9 — CHANGES_REQUESTED** [review]
The `version-regex` input has now been removed and replaced by `version` which is `PackageVersion` of manifests. If you want, I can merge this and you can update the rest of the things in another PR or as you feel comfortable.

**Comment by russellbanks** [comment]
> The `version-regex` input has now been removed and replaced by `version` which is `PackageVersion` of manifests. If you want, I can merge this and you can update the rest of the things in another PR or as you feel comfortable.

I'll update the rest at a later point. I'll be able to go over the other configuration options at that point too, like `fork-user`, etc.

**Review by vedantmgoyal9 — APPROVED** [review]

**Pull request merged**
